---
swagger: "2.0"
info:
  title: Find API
  description: API RESTful JSON para capturar e retornar a saída do comando Linux find.
  version: 1.0.0
host: 127.0.0.1:5000
schemes:
  - http
paths:
  /find:
    get:
      summary: Retorna o resultado da pesquisa de acordo com os parâmetros passados.
      description: Abaixo alguns exemplos de chamadas da API.
          
          1. http://127.0.0.1:5000/find?name=api&extensions=py,txt
          
          2. http://127.0.0.1:5000/find?name=api&extensions=py,txt&case_insensitive=true
          
          3. http://127.0.0.1:5000/find?name=api&modification_date=2022-01-02&dir=true
          
          4. http://127.0.0.1:5000/find?name=api&size=100250
      parameters:
        - in: query
          name: name
          required: true
          type: string
          description: Nome do arquivo ou pasta a ser pesquisado.
        - in: query
          name: case_insensitive
          required: false
          type: boolean
          enum: [true, false]
          default: false
          description: Verifica se vai ser uma pesquisa case insensitive ou case sensitive.
        - in: query
          name: exact_name
          required: false
          type: boolean
          enum: [true, false]
          default: false
          description: Verifica se vai ser pesquisado parte dos nome ou somente o nome.
        - in: query
          name: extensions
          required: false
          type: array
          items:
              type: string
          description: Array de extensões a serem usados na pesquisa.
            
            Exemplo [txt, zip, doc]
        - in: query
          name: modification_date
          required: false
          type: array
          items:
              type: string
          description: Uma só data ou um intervalo de datas. 
          
            Exemplo de data = YYYY-mm-DD = 2022-01-02 (na data brasileira equivale à 02/01/2022)
        - in: query
          name: size
          required: false
          type: string
          description: Tamanho do arquivo. 
                      
                      Se adicionado o sinal de adição (+) no inicio, irá ser procurado por arquivos com o tamanho maior do que o especificado, o mesmo acontece com o sinal de subtração (-), mas só que ao contrario. 
                      
                      Exemplo= +1234 ou -1234
        - in: query
          name: dir
          required: false
          type: boolean
          enum: [true, false]
          default: false
          description: Verifica se vai ser pesquisado as pastas também.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                path: 
                  type: string
                  format: int64
                  example: /home/user/arquivo.txt
                size ou count_files: 
                  type: integer
                  format: int64
                  example: caso seja um arquivo irá aparecer aqui o tamanho dele, caso contrario irá aparecer o total de arquivos na pasta
                creation_date:
                  type: integer
                  format: int64
                  example: data da criação em milissegundos
                isFile: 
                  type: boolean
                  format: int64
                  example: true se for um arquivo ou false caso contrario
        404:
          description: O arquivo/pasta não pode ser encontrado.